# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sitio web del proyecto Colibri
description: >- # this means to ignore newlines until "baseurl:"
  Proyecto Colibri
baseurl: "/colibri" # the subpath of the site
url: "https://jacalvache.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Inicio
      slug: /
    - name: Equipo
    - name: Publicaciones
    - name: Presentaciones
    - name: Posters
    - name: Podcast
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com
    #- name: WeChat
    #  value: YourWeChatUsername
    #  link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/YourTwitterUsername
      username: "@YourTwitterUsername"
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/YourGitHubUsername
    - name: Dribbble
      link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
